include:
  - ../../../base/freqtrade/compose.yml

services:
  freqtrade:
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "http://freqtrade:8080"
      caddy.tls: /certs/${CERT_DOMAIN}/fullchain.pem /certs/${CERT_DOMAIN}/privkey.pem
    networks:
      - caddy
    volumes:
      - ./priv_user_data:/freqtrade/user_data
    command: 
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
networks:
  caddy:
    external: true
