include:
  - ../../../base/knot/compose.yml
  - ../../../base/unbound/compose.yml

services:
  knot:
    volumes:
      - ./priv_knot.conf:/config/knot.conf
      - ./priv_zones:/zones
    ports:
      - "5300:53/udp"
      - "5300:53/tcp"
    networks:
      dns:
        ipv4_address: 172.20.53.10

  unbound:
    volumes:
      - ./priv_unbound:/opt/unbound/etc/unbound
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      dns:
        ipv4_address: 172.20.53.11

networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.53.0/24
          gateway: 172.20.53.1
