include:
  - ../../../base/knot/compose.yml
  - ../../../base/unbound/compose.yml

services:
  knot:
    volumes:
      - ./priv_knot.conf:/config/knot.conf
      - ./priv_zones:/zones
    networks:
      dns:
        ipv4_address: 172.20.0.10

  unbound:
    volumes:
      - ./priv_unbound:/opt/unbound/etc/unbound
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      dns:
        ipv4_address: 172.20.0.11

networks:
  dns:
