include:
  - ../../../base/mediamtx/compose.yml

services:
  mediamtx:
    ports:
      - 8554:8554
      - 8888:8888
      - 8889:8889
      - 8189:8189
    volumes:
      - ./priv_mediamtx.yml:/mediamtx.yml
