server:
  interface: 0.0.0.0@53
  interface: ::0@53

  interface: 0.0.0.0@853
  interface: ::0@853

  tls-service-pem: /etc/ssl/example.com/fullchain.pem
  tls-service-key: /etc/ssl/example.com/privkey.pem

  access-control: 0.0.0.0/0 allow

  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes

  qname-minimisation: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  hide-identity: yes
  hide-version: yes

  prefetch: yes
  cache-min-ttl: 300
  cache-max-ttl: 86400

  do-daemonize: no
  use-syslog: no
  logfile: ""

  verbosity: 4

  so-sndbuf: 0

forward-zone:
  name: "example."
  forward-addr: 203.0.113.1
