include:
  - ../../../base/gotosocial/compose.yml

services:
  gotosocial:
    labels:
      caddy_0: nbl.sh
      caddy_0.reverse_proxy: "http://gotosocial:8080"
      caddy_0.tls: /certs/nbl.sh/fullchain.pem /certs/nbl.sh/privkey.pem
      caddy_1: gts.nobell.fr
      caddy_1.reverse_proxy: "http://gotosocial:8080"
      caddy_1.tls: /certs/nobell.fr/fullchain.pem /certs/nobell.fr/privkey.pem
    env_file:
      - path: override.env
        required: true
    networks:
      - caddy
  gotosocial_elk:
    labels:
      caddy: social.nobell.fr
      caddy.reverse_proxy: "http://gotosocial_elk:5314"
      caddy.tls: /certs/nobell.fr/fullchain.pem /certs/nobell.fr/privkey.pem
    container_name: gotosocial_elk
    restart: unless-stopped
    image: ghcr.io/elk-zone/elk:v1.0.0
    environment:
      NUXT_PUBLIC_DEFAULT_SERVER: nobell.fr
      NITRO_LOG_LEVEL: "debug"
    volumes:
      - gotosocial_elk:/elk/data
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  gotosocial_elk:
