include:
  - ../../../base/sure/compose.yml

services:
  sure:
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "http://sure:3000"
      caddy.tls: /certs/${CERT_DOMAIN}/fullchain.pem /certs/${CERT_DOMAIN}/privkey.pem
    env_file:
      - path: override.env
        required: true
    networks:
      - caddy

  sure_db:
    env_file:
      - path: override.env
        required: true

networks:
  caddy:
    external: true
