services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: homepage
    restart: unless-stopped
    env_file:
      - path: default.env
        required: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
