services:
  homepage:
    image: gethomepage/homepage:v2.1.2
    container_name: homepage
    restart: unless-stopped
    env_file:
      - path: default.env
        required: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
