services:
  glances:
    image: nicolargo/glances:4.5.5
    container_name: glances
    restart: unless-stopped
    pid: host
    environment:
      GLANCES_OPT: -w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
