services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    networks:
      - searxng
    env_file:
      - path: default.env
        required: true
    volumes:
      - searxng_data:/var/cache/searxng

  searxng_valkey:
    image: valkey/valkey:9-alpine
    restart: unless-stopped
    container_name: searxng_valkey
    networks:
      - searxng
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - searxng_valkey:/data

volumes:
  searxng_data:
  searxng_valkey:

networks:
  searxng:
