services:
  gotosocial:
    image: docker.io/superseriousbusiness/gotosocial:0.22.1
    container_name: gotosocial
    restart: unless-stopped
    user: 1000:1000
    env_file:
      - path: default.env
        required: true
    volumes:
      - gotosocial_data:/gotosocial/storage
volumes:
  gotosocial_data:
