include:
  - ../../../base/unifi/compose.yml

services:
  unifi:
    env_file:
      - path: override.env
        required: true

  unifi_db:
    env_file:
      - path: override.env
        required: true
